version: 2.1

executors:
  ci-node:
    docker:
    - image: circleci/node:15-buster

jobs:
  deps-n-test:
    executor: ci-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths: ~/.cache/yarn
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn lint
    - run: yarn build
    - run: yarn test-types
    - run: yarn test
    - persist_to_workspace:
        root: .
        paths: '*'

  deploy-to-npm:
    executor: ci-node
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" > ~/.npmrc
    - run: npm publish


envs-matcher:
  build: &build
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/

  deploy: &deploy
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v?[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/

workflows:
  build_n_test_n_deploy:
    jobs:
    - deps-n-test:
        <<: *build
    - deploy-to-npm:
        <<: *deploy
        requires:
        - deps-n-test
