#!/usr/bin/env bash

## Script variables
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## Arg
PACKAGE_JSON_PATH=$1
NPM_ORG_SCOPE=$2
TARGET_TAG=$3

## Help
if [[ $# -ne 3 || $1 == '--help' || -z ${PACKAGE_JSON_PATH} || -z ${NPM_ORG_SCOPE} ]]; then
    echo "Push to npm"
    echo "Usage:    ./push_to_npm PACKAGE_JSON_PATH NPM_ORG_SCOPE TARGET_TAG"
    echo "Push to npm options:"
    echo "          --help"
    echo "Arguments description:"
    echo "PACKAGE_JSON_PATH must be a valid file path to a package.json"
    echo "NPM_ORG_SCOPE must be a valid npm organisation name"
    echo "TARGET_TAG must be a valid semver tag"
    exit 0
fi

## Check environment
if [[ -z ${NPM_TOKEN_PUBLISH} ]]; then
    echo "Please configure env variable: NPM_REGISTRY_PUBLISH"
    exit 1
fi

## Verify token exist in the current repo or add it to .npmrc
grep authToken ${DIR}/../../.npmrc >/dev/null 2>&1

if [[ $? -ne 0 ]]; then
    echo "Can't find a registry token, adding it to .npmrc ..."
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_PUBLISH}" >>${DIR}/../../.npmrc
else
    echo "Token found, processing ..."
fi

## Verify target org scope
if [ ! -f ${PACKAGE_JSON_PATH} ]; then
    echo "Can't find ${PACKAGE_JSON_PATH}. Exiting ..."
    exit 1
fi

packageJsonDir=$(dirname "${PACKAGE_JSON_PATH}")
echo "Moving to: ${packageJsonDir}"
cd ${packageJsonDir} && pwd

packageJsonScope=$(cat ${PACKAGE_JSON_PATH} | perl -n -e '/"name": "(.*)\/.*",/ && print $1')
echo "Package.json scope: ${packageJsonScope}, target scope is: @${NPM_ORG_SCOPE}"

if [[ ${packageJsonScope} != "@${NPM_ORG_SCOPE}" ]]; then
    echo "Scope don't match, please update your package.json. Exiting ..."
    exit 1
fi

## Verify tag
packageJsonTag=$(cat ${PACKAGE_JSON_PATH} | perl -n -e '/"version": "(.*)",/ && print $1')
echo "Package.json tag: ${packageJsonTag}, target tag: ${TARGET_TAG}"

if [[ ${TARGET_TAG} != ${packageJsonTag} ]]; then
    echo "Tag don't match, please update your package.json or push a correct tag. Exiting ..."
    exit 1
fi

## Publish
echo "Package.json OK, starting to push on NPM ..."
npm publish
