name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -  uses: actions/setup-node@v2
       with:
        node-version: 16
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm test


